name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: make build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::622473043539:role/DeployRole-bucketscan
          role-session-name: DeployFromBucketScanRepo
          aws-region: eu-west-2

      - run: aws s3 mb s3://slade-test
      - run: aws s3 rb s3://slade-test
